services:



  tri-api:
    image: tri-api:latest
    container_name: tri-api
    ports:
      - 8080:8080
    expose:
      - 8080
    env_file:
      - dev.env
    networks:
      - tri_network
    volumes:
      - .:/usr/src/app
    restart: unless-stopped


  tri-nginx:
    image: nginx:latest
    container_name: tri-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - tri-api
    networks:
      - tri_network
    restart: unless-stopped



  tri-api-mongodb:
    image: mongo:latest
    container_name: tri-api-mongodb
    env_file:
      - dev.env
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - tri_api_mongodb_data:/data/db
    networks:
      - tri_network
    restart: unless-stopped



  tri-api-rabbitmq:
    image: rabbitmq:3-management
    container_name: tri-api-rabbitmq
    env_file:
      - dev.env
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - tri_api_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - tri_network
    restart: unless-stopped



  tri-api-worker:
    image: tri-api:latest
    container_name: tri-api-worker
    entrypoint: []  
    command: [
      "celery",
      "--app=tri_api.celery.app.tri_api_celery_app",
      "worker",
      "--loglevel=INFO",
      "--queues=tri",
      "--without-gossip",
      "--without-mingle",
      "--without-heartbeat",
      "-Ofair",
      --pool=solo,
      "--hostname=tri_worker@%h",
      "--max-tasks-per-child=1000"
    ]
    working_dir: /usr/src/app 
    env_file:
      - dev.env
    volumes:
      - .:/usr/src/app
    networks:
      - tri_network
    depends_on:
      - tri-api-rabbitmq
      - tri-api-mongodb
      - tri-api
    restart: unless-stopped




volumes:
  tri_api_mongodb_data:
    name: tri_api_mongodb_data
  tri_api_rabbitmq_data:
    name: tri_api_rabbitmq_data


networks:
  tri_network:
    name: tri_network